/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clerk;

/**
 *
 * @author Asus
 */
public class Clerk_Office_Equipment extends javax.swing.JFrame {

    /**
     * Creates new form Clerak
     */
    public Clerk_Office_Equipment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coeout = new javax.swing.JButton();
        coein = new javax.swing.JButton();
        coereport = new javax.swing.JButton();
        coe_welcome_palel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        coe_out_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        coe_in_palel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        coe_report_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblBackgrround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coeout.setText("In");
        coeout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coeoutMouseClicked(evt);
            }
        });
        coeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeoutActionPerformed(evt);
            }
        });
        getContentPane().add(coeout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 70));

        coein.setText("Out");
        coein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeinActionPerformed(evt);
            }
        });
        getContentPane().add(coein, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 70));

        coereport.setText("Report");
        coereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coereportActionPerformed(evt);
            }
        });
        getContentPane().add(coereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 70));

        jLabel1.setText("Welcome to Office Equpment ");

        javax.swing.GroupLayout coe_welcome_palel1Layout = new javax.swing.GroupLayout(coe_welcome_palel1);
        coe_welcome_palel1.setLayout(coe_welcome_palel1Layout);
        coe_welcome_palel1Layout.setHorizontalGroup(
            coe_welcome_palel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_welcome_palel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        coe_welcome_palel1Layout.setVerticalGroup(
            coe_welcome_palel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_welcome_palel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        getContentPane().add(coe_welcome_palel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 980, 440));

        jLabel4.setText("Out panel");

        javax.swing.GroupLayout coe_out_panelLayout = new javax.swing.GroupLayout(coe_out_panel);
        coe_out_panel.setLayout(coe_out_panelLayout);
        coe_out_panelLayout.setHorizontalGroup(
            coe_out_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_out_panelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        coe_out_panelLayout.setVerticalGroup(
            coe_out_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_out_panelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(coe_out_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 980, 440));

        jLabel2.setText("In panel");

        javax.swing.GroupLayout coe_in_palelLayout = new javax.swing.GroupLayout(coe_in_palel);
        coe_in_palel.setLayout(coe_in_palelLayout);
        coe_in_palelLayout.setHorizontalGroup(
            coe_in_palelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_in_palelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        coe_in_palelLayout.setVerticalGroup(
            coe_in_palelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_in_palelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(coe_in_palel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 980, 440));

        jLabel3.setText("Report Pnal");

        javax.swing.GroupLayout coe_report_panelLayout = new javax.swing.GroupLayout(coe_report_panel);
        coe_report_panel.setLayout(coe_report_panelLayout);
        coe_report_panelLayout.setHorizontalGroup(
            coe_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_report_panelLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        coe_report_panelLayout.setVerticalGroup(
            coe_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coe_report_panelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(coe_report_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 980, 440));

        lblBackgrround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Session bg.png"))); // NOI18N
        lblBackgrround.setText("THI");
        getContentPane().add(lblBackgrround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeinActionPerformed
        // TODO add your handling code here:
        coe_welcome_palel1.setVisible(false);
        coe_report_panel.setVisible(false);
        coe_out_panel.setVisible(true);
        coe_in_palel.setVisible(false);
    }//GEN-LAST:event_coeinActionPerformed

    private void coereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coereportActionPerformed
        // TODO add your handling code here:
        coe_welcome_palel1.setVisible(false);
        coe_report_panel.setVisible(true);
        coe_out_panel.setVisible(false);
        coe_in_palel.setVisible(false);
    }//GEN-LAST:event_coereportActionPerformed

    private void coeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeoutActionPerformed
        // TODO add your handling code here:
        coe_welcome_palel1.setVisible(false);
        coe_report_panel.setVisible(false);
        coe_out_panel.setVisible(false);
        coe_in_palel.setVisible(true);
        
       
    }//GEN-LAST:event_coeoutActionPerformed

    private void coeoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coeoutMouseClicked
        
    }//GEN-LAST:event_coeoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clerk_Office_Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clerk_Office_Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clerk_Office_Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clerk_Office_Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clerk_Office_Equipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coe_in_palel;
    private javax.swing.JPanel coe_out_panel;
    private javax.swing.JPanel coe_report_panel;
    private javax.swing.JPanel coe_welcome_palel1;
    private javax.swing.JButton coein;
    private javax.swing.JButton coeout;
    private javax.swing.JButton coereport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBackgrround;
    // End of variables declaration//GEN-END:variables
}
