/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Database.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinet
 */
public class Admin_Dash extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dash
     */
    Connection con=null;
    public Admin_Dash() {
        initComponents();
        DBConnection dbcon=DBConnection.getDbConnect();
        this.con=dbcon.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddUser = new javax.swing.JLabel();
        lblUpdateUser = new javax.swing.JLabel();
        lblRemoveUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBackgrround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddUser.setBackground(new java.awt.Color(0, 0, 0));
        lblAddUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblAddUser.setForeground(new java.awt.Color(255, 255, 255));
        lblAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_30px.png"))); // NOI18N
        lblAddUser.setText("  Add User");
        lblAddUser.setToolTipText("");
        lblAddUser.setOpaque(true);
        lblAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddUserMouseExited(evt);
            }
        });
        getContentPane().add(lblAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 70));

        lblUpdateUser.setBackground(new java.awt.Color(0, 0, 0));
        lblUpdateUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_30px.png"))); // NOI18N
        lblUpdateUser.setText("Update User");
        lblUpdateUser.setToolTipText("");
        lblUpdateUser.setOpaque(true);
        lblUpdateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdateUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdateUserMouseExited(evt);
            }
        });
        getContentPane().add(lblUpdateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 70));

        lblRemoveUser.setBackground(new java.awt.Color(0, 0, 0));
        lblRemoveUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblRemoveUser.setForeground(new java.awt.Color(255, 255, 255));
        lblRemoveUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemoveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_minus_30px_1.png"))); // NOI18N
        lblRemoveUser.setText("Remove User");
        lblRemoveUser.setToolTipText("");
        lblRemoveUser.setOpaque(true);
        lblRemoveUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemoveUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemoveUserMouseExited(evt);
            }
        });
        getContentPane().add(lblRemoveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 70));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_shutdown_30px.png"))); // NOI18N
        lblLogout.setText("      Logout");
        lblLogout.setToolTipText("");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 70));

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153,10));
        jScrollPane1.setBorder(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(0, 0, 0,0));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ID", "Name", "Position", "Password", "Contact", "Email", "NIC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 820, 390));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255,255,255));

        lblBackgrround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Session bg.png"))); // NOI18N
        getContentPane().add(lblBackgrround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddUserMouseEntered
        lblAddUser.setBackground(new java.awt.Color(50, 50, 50));
        lblAddUser.setFont(new java.awt.Font("Trebuchet MS", 0, 20));
    }//GEN-LAST:event_lblAddUserMouseEntered

    private void lblAddUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddUserMouseExited
        lblAddUser.setBackground(new java.awt.Color(0, 0, 0));
        lblAddUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
    }//GEN-LAST:event_lblAddUserMouseExited

    private void lblUpdateUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateUserMouseEntered
        lblUpdateUser.setBackground(new java.awt.Color(50, 50, 50));
        lblUpdateUser.setFont(new java.awt.Font("Trebuchet MS", 0, 20));
    }//GEN-LAST:event_lblUpdateUserMouseEntered

    private void lblUpdateUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateUserMouseExited
        lblUpdateUser.setBackground(new java.awt.Color(0, 0, 0));
        lblUpdateUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
    }//GEN-LAST:event_lblUpdateUserMouseExited

    private void lblRemoveUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveUserMouseEntered
        lblRemoveUser.setBackground(new java.awt.Color(50, 50, 50));
        lblRemoveUser.setFont(new java.awt.Font("Trebuchet MS", 0, 20));
    }//GEN-LAST:event_lblRemoveUserMouseEntered

    private void lblRemoveUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveUserMouseExited
        lblRemoveUser.setBackground(new java.awt.Color(0, 0, 0));
        lblRemoveUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
    }//GEN-LAST:event_lblRemoveUserMouseExited

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBackground(new java.awt.Color(50, 50, 50));
        lblLogout.setFont(new java.awt.Font("Trebuchet MS", 0, 20));
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Trebuchet MS", 0, 18));    }//GEN-LAST:event_lblLogoutMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
        jTable1.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        jTable1.setAlignmentY(CENTER_ALIGNMENT);
        DefaultTableModel model=null;
        String sql="select * from user";
        try {
            Statement stmt=con.createStatement();
            ResultSet res=stmt.executeQuery(sql);
            int count=0;
            while(res.next()){
                count++;
                Object row[] = {count, res.getString(1),res.getString(2),res.getString(7),res.getString(3),res.getString(4),res.getString(5),res.getString(6)};
                model = (DefaultTableModel) jTable1.getModel();
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
    }//GEN-LAST:event_formWindowOpened

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddUser;
    private javax.swing.JLabel lblBackgrround;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblRemoveUser;
    private javax.swing.JLabel lblUpdateUser;
    // End of variables declaration//GEN-END:variables
}
